C     MOLECULE COMMON
C
C     Common definition for molecule data 
C
C     ------------------------------------------------------------------
C
      INTEGER PSHELL(MXSH,3),NSTO,COP(0:MXL,0:MXL,0:MXL),
     $        DSHL,NATOM,SOP(0:MXL,0:MXL,0:MXL),NSHL,GLL(MXSH),
     $        LLS(MXATM),GUL(MXSH),ULS(MXATM),ULSTO(MXSH),LLSTO(MXSH),
     $        NELEC,SLL(MXSH),SUL(MXSH),NSPH,LM
      COMMON /IMOLECULED/ PSHELL,NSTO,COP,DSHL,NATOM,SOP,NSHL,GLL,
     $                    LLS,GUL,ULS,ULSTO,LLSTO,NELEC,SLL,SUL,NSPH,LM
C
      REAL ZET(MXGTF),SDISTANCE(MXATM,MXATM),
     $     INTHRESH,INTHRESH2,RAB(3),RCD(3),RAC(3),RBC(3),RSQAB,RSQCD,
     $     NCSTO(MXSTO),MS(3),AAT(3),BAT(3),CAT(3),DAT(3),ENERTWO(3),
     $     PRODAT,PRODBT,ENERTWOAU(3),TOLTIME,CPUT,ENER(3),ENERD(3)
      COMMON /RMOLECULED/ ZET,SDISTANCE,INTHRESH,INTHRESH2,
     $                    RAB,RCD,RAC,RBC,RSQAB,RSQCD,NCSTO,MS,AAT,BAT,
     $                    CAT,DAT,ENERTWO,PRODAT,PRODBT,ENERTWOAU,
     $                    TOLTIME,CPUT,ENER,ENERD
C
